integrating additional commands for OXS Metal

diff --git a/.yamato/urp_performance_boatattack-osx-metal.yml b/.yamato/urp_performance_boatattack-osx-metal.yml
--- a/.yamato/urp_performance_boatattack-osx-metal.yml
+++ b/.yamato/urp_performance_boatattack-osx-metal.yml
@@ -22,7 +22,7 @@ URP_Performance_BoatAttack_OSX_Metal_performance_playmode_runtime_mono_Linear_tr
         UTR_VERSION: "current"
         TEST_FILTER: .*
     commands:
-      -  git clone https://github.com/Unity-Technologies/BoatAttack.git -b $BOAT_ATTACK_BRANCH TestProjects/BoatAttack
+      -  git clone https://github.com/Unity-Technologies/BoatAttack.git -b $BOAT_ATTACK_BRANCH $YAMATO_SOURCE_DIR/TestProjects/BoatAttack
       -  cd TestProjects/BoatAttack && git checkout $BOAT_ATTACK_REVISION
       -  brew tap --force-auto-update unity/unity git@github.cds.internal.unity3d.com:unity/homebrew-unity.git
       -  brew install unity-config
@@ -44,30 +44,152 @@ URP_Performance_BoatAttack_OSX_Metal_performance_playmode_runtime_mono_Linear_tr
       -  cd TestProjects/BoatAttack && unity-config project add testable com.unity.render-pipelines.core  --project-path .
       -  cd TestProjects/BoatAttack && unity-config project add testable unity.graphictests.performance.universal  --project-path .
       -  cd TestProjects/BoatAttack && unity-config project set project-update false --project-path .
-      -  curl -s https://artifactory.prd.it.unity3d.com/artifactory/unity-tools-local/utr-standalone/utr --output utr
-      -  chmod +x utr
-      -  scp -i ~/.ssh/id_rsa_macmini -r $YAMATO_SOURCE_DIR bokken@$BOKKEN_DEVICE_IP:~/Graphics
-      -  scp -i ~/.ssh/id_rsa_macmini ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP:~/.ssh/id_rsa_macmini
-      -  ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "bash -lc 'pip3 install unity-downloader-cli --user --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade'"
-      -  ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP '$(python3 -m site --user-base)/bin/unity-downloader-cli --source-file ~/Graphics/unity_revision.txt -c editor -c il2cpp  --wait --published-only'
-      -  |5-
-              ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "export UPM_REGISTRY=https://artifactory-slo.bf.unity3d.com/artifactory/api/npm/upm-candidates; ~/Graphics/utr  --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results --category=URP --editor-location=.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-scriptingbackend=Mono2x" --performance-project-id=BoatAttack --platform=StandaloneOSX --report-performance-data --scripting-backend=Mono2x --suite=playmode --testfilter=Low --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack --timeout=1200 --zero-tests-are-ok=1 "
-              UTR_RESULT=$?
-              mkdir -p TestProjects/BoatAttack/test-results/
-              scp -i ~/.ssh/id_rsa_macmini -r bokken@$BOKKEN_DEVICE_IP:/Users/bokken/Graphics/TestProjects/BoatAttack/test-results/ TestProjects/BoatAttack/test-results/
-              exit $UTR_RESULT
-      -  |5-
-              ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "export UPM_REGISTRY=https://artifactory-slo.bf.unity3d.com/artifactory/api/npm/upm-candidates; ~/Graphics/utr  --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results --category=URP --editor-location=.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-scriptingbackend=Mono2x" --performance-project-id=BoatAttack --platform=StandaloneOSX --report-performance-data --scripting-backend=Mono2x --suite=playmode --testfilter=Medium --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack --timeout=1200 --zero-tests-are-ok=1 "
-              UTR_RESULT=$?
-              mkdir -p TestProjects/BoatAttack/test-results/
-              scp -i ~/.ssh/id_rsa_macmini -r bokken@$BOKKEN_DEVICE_IP:/Users/bokken/Graphics/TestProjects/BoatAttack/test-results/ TestProjects/BoatAttack/test-results/
-              exit $UTR_RESULT
-      -  |5-
-              ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "export UPM_REGISTRY=https://artifactory-slo.bf.unity3d.com/artifactory/api/npm/upm-candidates; ~/Graphics/utr  --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results --category=URP --editor-location=.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-scriptingbackend=Mono2x" --performance-project-id=BoatAttack --platform=StandaloneOSX --report-performance-data --scripting-backend=Mono2x --suite=playmode --testfilter=High --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack --timeout=1200 --zero-tests-are-ok=1 "
-              UTR_RESULT=$?
-              mkdir -p TestProjects/BoatAttack/test-results/
-              scp -i ~/.ssh/id_rsa_macmini -r bokken@$BOKKEN_DEVICE_IP:/Users/bokken/Graphics/TestProjects/BoatAttack/test-results/ TestProjects/BoatAttack/test-results/
-              exit $UTR_RESULT
+      
+      # Debug stuff.
+      - env | sort
+
+      # Fix SSH config on the VM. The Bokken team is fixing this in the base images.
+      - sed -i '' 's/172\.28\.218\.\*/172\.28\.224\.\*/g' ~/.ssh/config
+
+      # Cleanup stuff for a Yamato Remote re-run. Only delete the source dir on the device if you really need to wipe it.
+      - ssh bokken@$BOKKEN_DEVICE_IP "rm -rf ~/.ssh/id_rsa_cds_github ~/.ssh/config ~/.utr_result ~/setup_codesign.sh"
+      - rm -rf ~/.utr_result
+      # - ssh bokken@$BOKKEN_DEVICE_IP "rm -rf ~/RepoName"
+
+      # Setup SSH config. Sets the key to use for github.cds.internal.unity3d.com.
+      - scp .yamato/files/ssh-config bokken@$BOKKEN_DEVICE_IP:~/.ssh/config
+
+      # Get Github CDS SSH privkey.
+      - echo $SEANS_KEY | base64 -D -i - -o id_rsa_cds_github
+      - scp id_rsa_cds_github bokken@$BOKKEN_DEVICE_IP:~/.ssh/id_rsa_cds_github
+      - ssh bokken@$BOKKEN_DEVICE_IP "chmod 400 ~/.ssh/*"
+
+      # Get UTR into the test folder.
+      - curl -s https://artifactory.internal.unity3d.com/core-automation/tools/utr-standalone/utr --output $YAMATO_SOURCE_DIR/TestProjects/BoatAttack/utr
+      - chmod +x $YAMATO_SOURCE_DIR/TestProjects/BoatAttack/utr
+      
+      # -  curl -s https://artifactory.prd.it.unity3d.com/artifactory/unity-tools-local/utr-standalone/utr --output utr
+      # -  chmod +x utr
+      
+      # Upload the RepoName repo to the device or update it. The folder will be at ~/RepoName in the remote. Ignore dot files to keep it snappy (especially for Yamato Remote).
+    - rsync -uaqP --exclude=".*" --inplace $YAMATO_SOURCE_DIR bokken@$BOKKEN_DEVICE_IP:~/
+
+    # Install the Unity Downloader.
+    - ssh bokken@$BOKKEN_DEVICE_IP "bash -lc 'pip3 install unity-downloader-cli --user --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade'"    
+      
+      # -  scp -i ~/.ssh/id_rsa_macmini -r $YAMATO_SOURCE_DIR bokken@$BOKKEN_DEVICE_IP:~/Graphics
+      # -  scp -i ~/.ssh/id_rsa_macmini ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP:~/.ssh/id_rsa_macmini
+      # -  ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "bash -lc 'pip3 install unity-downloader-cli --user --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade'"      
+      
+      # Get the Editor and required components for the project. This will be rendered as a single line command. Beware of the quotes! They bite, repeatedly. :(
+    - >
+        ssh bokken@$BOKKEN_DEVICE_IP
+        "\$(/usr/local/bin/python3 -m site --user-base)/bin/unity-downloader-cli    \\
+            --source-file ~/Graphics/unity_revision.txt                             \\
+            -c editor                                                               \\
+            -c il2cpp                                                               \\
+            --wait                                                                  \\
+            --published-only"      
+
+    # Setup app signing.
+    - scp $YAMATO_SOURCE_DIR/.yamato/files/setup_codesign.sh bokken@$BOKKEN_DEVICE_IP:~/setup_codesign.sh
+    - ssh bokken@$BOKKEN_DEVICE_IP "bash ~/setup_codesign.sh"
+
+      # -  ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP '$(python3 -m site --user-base)/bin/unity-downloader-cli --source-file ~/Graphics/unity_revision.txt -c editor -c il2cpp  --wait --published-only'
+      # -  |5-
+              # export GIT_REVISIONDATE=`git rev-parse HEAD | git show -s --format=%cI`
+              # ./utr --artifacts_path=TestProjects/BoatAttack/test-results --build-only --category=URP --editor-location=.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-buildtarget" --extra-editor-arg="StandaloneOSX" --extra-editor-arg="-colorspace=Linear" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-playergraphicsapi=Metal" --extra-editor-arg="-scriptingbackend=mono" --platform=StandaloneOSX --player-save-path=playersLow --scripting-backend=mono --suite=playmode --testfilter=Low --testproject=./TestProjects/BoatAttack --timeout=1200
+                         
+    # Build on the device and capture exit code. This will be rendered as a single line command. Beware of the backslashes and the semicolons too.
+    - >
+        ssh bokken@$BOKKEN_DEVICE_IP
+        "export UPM_REGISTRY=$UPM_REGISTRY;
+        echo ==================================================;
+        echo UPM Registry: \$UPM_REGISTRY;
+        echo ==================================================;
+        cd ~/Graphics/TestProjects/BoatAttack
+        export GIT_REVISIONDATE=`git rev-parse HEAD | git show -s --format=%cI`
+        ./utr                                                                                           \\
+            --artifacts_path=$YAMATO_SOURCE_DIR/TestProjects/BoatAttack/test-results                                       \\
+            --build-only                                                                                \\
+            --category=URP                                                                              \\
+            --editor-location=.Editor                                                                   \\
+            --extra-editor-arg="-colorspace=Linear"                                                     \\
+            --extra-editor-arg="-buildtarget"                                                           \\
+            --extra-editor-arg="StandaloneOSX"                                                          \\
+            --extra-editor-arg="-executemethod"                                                         \\
+            --extra-editor-arg="Editor.Setup"                                                           \\
+            --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity"   \\
+            --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH"                                    \\
+            --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal"             \\
+            --extra-editor-arg="-packageundertestrev=$GIT_REVISION"                                     \\
+            --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE"                             \\
+            --extra-editor-arg="-playergraphicsapi=Metal"                                               \\
+            --extra-editor-arg="-scriptingbackend=mono"                                                 \\
+            --platform=StandaloneOSX                                                                    \\
+            --player-save-path=playersLow                                                               \\
+            --scripting-backend=Mono2x                                                                  \\
+            --suite=playmode                                                                            \\ 
+            --testfilter=Low                                                                            \\
+            --testproject=~/Graphics/TestProjects/BoatAttack                                                    \\
+            --timeout=2400                                                                              \\
+
+        echo \$? > ~/.utr_result"
+
+    # Read UTR result and data from test device.
+    - scp bokken@$BOKKEN_DEVICE_IP:~/.utr_result ~/.utr_result
+
+    # Print status and exit with UTR's exit code.
+    - |
+        UTR_RESULT=$(cat ~/.utr_result)
+        echo "=================================================="
+        echo "UTR build exit code: $UTR_RESULT"
+        echo "=================================================="
+        if [ "$UTR_RESULT" != "0" ]; then exit $UTR_RESULT; fi
+              
+              
+              
+      
+      # -  |5-
+              # ssh -i ~/.ssh/id_rsa_macmini bokken@$BOKKEN_DEVICE_IP "export UPM_REGISTRY=https://artifactory-slo.bf.unity3d.com/artifactory/api/npm/upm-candidates; ~/Graphics/utr  --artifacts_path=/Users/bokken/Graphics/TestProjects/BoatAttack/test-results --category=URP --editor-location=.Editor --extra-editor-arg="-addscenetobuild=Assets/scenes/Testing/benchmark_island-static.unity" --extra-editor-arg="-executemethod" --extra-editor-arg="Editor.Setup" --extra-editor-arg="-packageundertestbranch=$GIT_BRANCH" --extra-editor-arg="-packageundertestname=com.unity.render-pipelines.universal" --extra-editor-arg="-packageundertestrev=$GIT_REVISION" --extra-editor-arg="-packageundertestrevdate=$GIT_REVISIONDATE" --extra-editor-arg="-scriptingbackend=Mono2x" --performance-project-id=BoatAttack --platform=StandaloneOSX --report-performance-data --scripting-backend=Mono2x --suite=playmode --testfilter=Low --testproject=/Users/bokken/Graphics/TestProjects/BoatAttack --timeout=1200 --zero-tests-are-ok=1 "
+              # UTR_RESULT=$?
+              # mkdir -p TestProjects/BoatAttack/test-results/
+              # scp -i ~/.ssh/id_rsa_macmini -r bokken@$BOKKEN_DEVICE_IP:/Users/bokken/Graphics/TestProjects/BoatAttack/test-results/ TestProjects/BoatAttack/test-results/
+              # exit $UTR_RESULT
+              
+    # Run tests on the device and capture exit code. This will be rendered as a single line command. Beware of the backslashes and the semicolons too.
+    - >
+        ssh bokken@$BOKKEN_DEVICE_IP
+        "export UPM_REGISTRY=$UPM_REGISTRY;
+        echo ==================================================;
+        echo UPM Registry: \$UPM_REGISTRY;
+        echo ==================================================;
+        cd ~/Graphics/TestProjects/BoatAttack/;
+        ./utr                                     \\
+            --artifacts_path=test-results         \\
+            --category=URP                                                                       \\
+            --platform=StandaloneOSX              \\
+            --player-connection-ip=auto           \\
+            --player-load-path=playersLow          \\
+            --performance-project-id=BoatAttack    \\
+            --report-performance-data               
+            --reruncount=2                        \\
+            --suite=playmode                      \\
+            --timeout=2400;
+        echo \$? > ~/.utr_result"
+    
+    # Read UTR result and data from test device.
+    - scp bokken@$BOKKEN_DEVICE_IP:~/.utr_result ~/.utr_result
+    - rsync -aqP bokken@$BOKKEN_DEVICE_IP:~/Graphics/TestProjects/BoatAttack/test-results $YAMATO_SOURCE_DIR/TestProjects/BoatAttack/
+
+    # Print status and exit with UTR's exit code.
+    - |
+        UTR_RESULT=$(cat ~/.utr_result)
+        echo "=================================================="
+        echo "UTR test exit code: $UTR_RESULT"
+        echo "=================================================="
+        exit $UTR_RESULT
+        
     artifacts:
         logs:
             paths:
